name: Issue report
on: [issues, workflow_dispatch]
jobs:
   Report:
      name: report issues
      runs-on: ubuntu-latest
      steps:
         - name: report event
           run: echo "${{toJson(github.event)}}"