name: lint,test,deploy
on: [push, workflow_dispatch]
jobs:
   test:
      name: Test
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout repo
            uses: actions/checkout@v3


